apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nginx:1.25
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 128Mi
        ports:
        - containerPort: 80
